### ISSUE TITLE
Specimen detail view throws error

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/eMaapou#960]
https://geoloogia.info/specimen/285129/git-426-174

TypeError: Cannot read properties of null (reading 'value')
    at fn (f0dfa8b.js:1:18155)
    at Object.o [as column-left] (9cf225e.js:2:21619)
    at 852d263.js:1:8453
    at f.We [as _t] (9cf225e.js:2:18768)
    at f.<anonymous> (852d263.js:1:8356)
    at t._render (9cf225e.js:2:48090)
    at f.r (9cf225e.js:2:78481)
    at t.get (9cf225e.js:2:28348)
    at t.run (9cf225e.js:2:29081)
    at Lr (9cf225e.js:2:31049)

**Comment by Erikdzo** [comment]
this seems to be fixed
